/**
 * Wails-generated bindings for the Go App struct.
 * This file is auto-generated by `wails dev` / `wails build`.
 * It is checked in here as a stub that works identically —
 * the real generated file will be placed here during `wails build`.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const _app = (): any => (window as any)['go']?.['main']?.['App'];

export function CreateCollection(name: string): Promise<import('../../../types/collection').Collection> {
  return _app()?.CreateCollection(name);
}

export function ListCollections(): Promise<import('../../../types/collection').Collection[]> {
  return _app()?.ListCollections();
}

export function RenameCollection(id: string, name: string): Promise<void> {
  return _app()?.RenameCollection(id, name);
}

export function DeleteCollection(id: string): Promise<void> {
  return _app()?.DeleteCollection(id);
}

export function CreateRequest(collectionId: string, name: string): Promise<import('../../../types/request').Request> {
  return _app()?.CreateRequest(collectionId, name);
}

export function ListRequests(collectionId: string): Promise<import('../../../types/request').Request[]> {
  return _app()?.ListRequests(collectionId);
}

export function GetRequest(id: string): Promise<import('../../../types/request').Request> {
  return _app()?.GetRequest(id);
}

export interface RequestPayload {
  id: string;
  method: string;
  url: string;
  headers: string;
  params: string;
  body_type: string;
  body: string;
}

export function UpdateRequest(payload: RequestPayload): Promise<void> {
  return _app()?.UpdateRequest(payload);
}

export interface ResponseResult {
  StatusCode: number;
  StatusText: string;
  Body: string;
  Headers: Record<string, string[]>;
  DurationMs: number;
  SizeBytes: number;
}

export function SendRequest(id: string): Promise<ResponseResult> {
  return _app()?.SendRequest(id);
}

export function CreateEnvironment(name: string): Promise<import('../../../types/environment').Environment> {
  return _app()?.CreateEnvironment(name);
}

export function ListEnvironments(): Promise<import('../../../types/environment').Environment[]> {
  return _app()?.ListEnvironments();
}

export function RenameEnvironment(id: string, name: string): Promise<void> {
  return _app()?.RenameEnvironment(id, name);
}

export function DeleteEnvironment(id: string): Promise<void> {
  return _app()?.DeleteEnvironment(id);
}

export function GetActiveEnvironment(): Promise<string> {
  return _app()?.GetActiveEnvironment();
}

export function SetActiveEnvironment(id: string): Promise<void> {
  return _app()?.SetActiveEnvironment(id);
}

export interface EnvironmentVariable {
  id: number;
  environment_id: string;
  key: string;
  value: string;
}

export function SetVariable(environmentId: string, key: string, value: string): Promise<EnvironmentVariable> {
  return _app()?.SetVariable(environmentId, key, value);
}

export function GetVariables(environmentId: string): Promise<EnvironmentVariable[]> {
  return _app()?.GetVariables(environmentId);
}

export function DeleteVariable(id: number): Promise<void> {
  return _app()?.DeleteVariable(id);
}
