/**
 * Wails-generated bindings for the Go App struct.
 * This file is auto-generated by `wails dev` / `wails build`.
 * It is checked in here as a stub that works identically —
 * the real generated file will be placed here during `wails build`.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const { go }: any = (window as any).wails ?? { go: {} };

export function CreateCollection(name: string): Promise<import('../../../types/collection').Collection> {
  return go?.main?.App?.CreateCollection(name);
}

export function ListCollections(): Promise<import('../../../types/collection').Collection[]> {
  return go?.main?.App?.ListCollections();
}

export function RenameCollection(id: string, name: string): Promise<void> {
  return go?.main?.App?.RenameCollection(id, name);
}
