/**
 * Wails-generated bindings for the Go App struct.
 * This file is auto-generated by `wails dev` / `wails build`.
 * It is checked in here as a stub that works identically —
 * the real generated file will be placed here during `wails build`.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const _app = (): any => (window as any)['go']?.['main']?.['App'];

export function CreateCollection(name: string): Promise<import('../../../types/collection').Collection> {
  return _app()?.CreateCollection(name);
}

export function ListCollections(): Promise<import('../../../types/collection').Collection[]> {
  return _app()?.ListCollections();
}

export function RenameCollection(id: string, name: string): Promise<void> {
  return _app()?.RenameCollection(id, name);
}

export function DeleteCollection(id: string): Promise<void> {
  return _app()?.DeleteCollection(id);
}

export function CreateRequest(collectionId: string, name: string): Promise<import('../../../types/request').Request> {
  return _app()?.CreateRequest(collectionId, name);
}

export function ListRequests(collectionId: string): Promise<import('../../../types/request').Request[]> {
  return _app()?.ListRequests(collectionId);
}

// RenameRequest validates the new name and updates the request in SQLite.
export function RenameRequest(id: string, name: string): Promise<void> {
  return _app()?.RenameRequest(id, name);
}

export function GetRequest(id: string): Promise<import('../../../types/request').Request> {
  return _app()?.GetRequest(id);
}

export interface RequestPayload {
  id: string;
  method: string;
  url: string;
  headers: string;
  params: string;
  body_type: string;
  body: string;
  auth_type: string;
  auth_config: string;
  timeout_seconds: number;
  tests: string;
  pre_script: string;
  post_script: string;
}

export function UpdateRequest(payload: RequestPayload): Promise<void> {
  return _app()?.UpdateRequest(payload);
}

export function DeleteRequest(id: string): Promise<void> {
  return _app()?.DeleteRequest(id);
}

export function DuplicateRequest(requestId: string): Promise<import('../../../types/request').Request> {
  return _app()?.DuplicateRequest(requestId);
}

export interface SearchResult {
  request_id: string;
  request_name: string;
  method: string;
  url: string;
  collection_id: string;
  collection_name: string;
}

export function SearchRequests(query: string): Promise<SearchResult[]> {
  return _app()?.SearchRequests(query);
}

export function SearchRequestsWithBody(query: string): Promise<SearchResult[]> {
  return _app()?.SearchRequestsWithBody(query);
}

export interface ResponseResult {
  StatusCode: number;
  StatusText: string;
  Body: string;
  Headers: Record<string, string[]>;
  DurationMs: number;
  SizeBytes: number;
  consoleLogs: string[];
  scriptErrors: string[];
  Timing?: import('../../../types/timing').TimingPhases;
}

export function SendRequest(id: string): Promise<ResponseResult> {
  return _app()?.SendRequest(id);
}

export function CreateEnvironment(name: string): Promise<import('../../../types/environment').Environment> {
  return _app()?.CreateEnvironment(name);
}

export function ListEnvironments(): Promise<import('../../../types/environment').Environment[]> {
  return _app()?.ListEnvironments();
}

export function RenameEnvironment(id: string, name: string): Promise<void> {
  return _app()?.RenameEnvironment(id, name);
}

export function DeleteEnvironment(id: string): Promise<void> {
  return _app()?.DeleteEnvironment(id);
}

export function GetGlobalEnvironmentID(): Promise<string> {
  return _app()?.GetGlobalEnvironmentID();
}

export function GetActiveEnvironment(): Promise<string> {
  return _app()?.GetActiveEnvironment();
}

export function SetActiveEnvironment(id: string): Promise<void> {
  return _app()?.SetActiveEnvironment(id);
}

export interface EnvironmentVariable {
  id: number;
  environment_id: string;
  key: string;
  value: string;
  is_secret: boolean;
  /** Set by the Go backend when it could not decrypt the stored ciphertext. */
  broken?: boolean;
}

export function SetVariable(environmentId: string, key: string, value: string, isSecret: boolean): Promise<EnvironmentVariable> {
  return _app()?.SetVariable(environmentId, key, value, isSecret);
}

export function GetVariables(environmentId: string): Promise<EnvironmentVariable[]> {
  return _app()?.GetVariables(environmentId);
}

export function DeleteVariable(id: number): Promise<void> {
  return _app()?.DeleteVariable(id);
}

export interface HistoryEntry {
  id: number;
  method: string;
  url: string;
  headers: string;
  params: string;
  body_type: string;
  body: string;
  response_status: number;
  response_body: string;
  response_headers: string;
  response_duration_ms: number;
  response_size_bytes: number;
  executed_at: string;
}

export function GetHistory(): Promise<HistoryEntry[]> {
  return _app()?.GetHistory();
}

export function ClearHistory(): Promise<void> {
  return _app()?.ClearHistory();
}

export function ExportCollection(collectionId: string): Promise<void> {
  return _app()?.ExportCollection(collectionId);
}

export function ImportCollection(): Promise<import('../../../types/collection').Collection> {
  return _app()?.ImportCollection();
}

export function CreateFolder(collectionId: string, parentFolderId: string, name: string): Promise<import('../../../types/folder').Folder> {
  return _app()?.CreateFolder(collectionId, parentFolderId, name);
}

export function RenameFolder(id: string, name: string): Promise<void> {
  return _app()?.RenameFolder(id, name);
}

export function DeleteFolder(id: string): Promise<void> {
  return _app()?.DeleteFolder(id);
}

export function ListFolders(collectionId: string): Promise<import('../../../types/folder').Folder[]> {
  return _app()?.ListFolders(collectionId);
}

export function CreateRequestInFolder(collectionId: string, folderId: string, name: string): Promise<import('../../../types/request').Request> {
  return _app()?.CreateRequestInFolder(collectionId, folderId, name);
}

export function MoveRequest(requestId: string, folderId: string): Promise<void> {
  return _app()?.MoveRequest(requestId, folderId);
}

export function MoveRequestToCollection(requestId: string, targetCollectionId: string, targetFolderId: string): Promise<void> {
  return _app()?.MoveRequestToCollection(requestId, targetCollectionId, targetFolderId);
}

export function GetSetting(key: string): Promise<string> {
  return _app()?.GetSetting(key);
}

export function SetSetting(key: string, value: string): Promise<void> {
  return _app()?.SetSetting(key, value);
}

export function ExportRequestAsCurl(id: string): Promise<string> {
  return _app()?.ExportRequestAsCurl(id);
}

export function ImportFromCurl(collectionId: string, curlCommand: string): Promise<import('../../../types/request').Request> {
  return _app()?.ImportFromCurl(collectionId, curlCommand);
}

export interface RunResult {
  RequestId: string;
  RequestName: string;
  Status: number;
  DurationMs: number;
  Passed: boolean;
  Error: string;
}

export function RunCollection(collectionId: string, requestIds: string[], delayMs: number): Promise<RunResult[]> {
  return _app()?.RunCollection(collectionId, requestIds, delayMs);
}

export function CancelRun(): Promise<void> {
  return _app()?.CancelRun();
}

// SetSecretVariable encrypts value and upserts it as a secret variable.
// After calling this the frontend store should re-fetch the variable list.
export function SetSecretVariable(envId: string, key: string, value: string): Promise<void> {
  return _app()?.SetSecretVariable(envId, key, value);
}

// GetDecryptedVariable fetches and decrypts the variable identified by key
// inside envId. Returns the plaintext value.
export function GetDecryptedVariable(envId: string, key: string): Promise<string> {
  return _app()?.GetDecryptedVariable(envId, key);
}

// ToggleVariableSecret changes the secret flag for the variable identified by
// varId. Pass isSecret=true to encrypt the stored value; false to store it as
// plaintext. After calling this the frontend store should re-fetch the variable
// list.
export function ToggleVariableSecret(varId: number, isSecret: boolean): Promise<void> {
  return _app()?.ToggleVariableSecret(varId, isSecret);
}

// RotateVarEncryptionKey generates a new AES key, re-encrypts all secret
// variables in a single DB transaction, and updates the OS keychain.
// Not wired to any frontend UI — callable via IPC (known limitation).
export function RotateVarEncryptionKey(): Promise<void> {
  return _app()?.RotateVarEncryptionKey();
}

// ReorderRequests updates sort_order for requests in a folder (or root level if folderID = "").
export function ReorderRequests(folderId: string, requestIds: string[]): Promise<void> {
  return _app()?.ReorderRequests(folderId, requestIds);
}

export interface ImportResult {
  CollectionID: string;
  RequestCount: number;
  FolderCount: number;
}

// PickOpenAPIFile opens a native file dialog for selecting an OpenAPI / Swagger
// spec file (.yaml, .yml, .json). Returns the selected file path, or an empty
// string if the user cancelled.
export function PickOpenAPIFile(): Promise<string> {
  return _app()?.PickOpenAPIFile();
}

// ImportOpenAPISpec parses an OpenAPI 3.x or Swagger 2.0 spec at filePath.
// Returns ImportConflict-shaped error string when a collection with the same
// name already exists (error message matches: "import conflict: ...").
export function ImportOpenAPISpec(filePath: string): Promise<ImportResult> {
  return _app()?.ImportOpenAPISpec(filePath);
}

// ImportOpenAPISpecWithResolution resolves a conflict from ImportOpenAPISpec.
// resolution must be one of: "merge", "replace", "copy".
export function ImportOpenAPISpecWithResolution(filePath: string, resolution: string): Promise<ImportResult> {
  return _app()?.ImportOpenAPISpecWithResolution(filePath, resolution);
}

export function ExportCollectionAsOpenAPI(collectionId: string): Promise<string> {
  return _app()?.ExportCollectionAsOpenAPI(collectionId);
}

export function ExportCollectionAsOpenAPIToFile(collectionId: string): Promise<void> {
  return _app()?.ExportCollectionAsOpenAPIToFile(collectionId);
}
