/**
 * Stub type models for CI builds.
 * In development, this file is auto-generated by `wails dev` / `wails build`.
 * This stub provides the type definitions so TypeScript can compile in CI
 * without running the full Wails build.
 */

export namespace main {
  export interface RequestPayload {
    id: string;
    method: string;
    url: string;
    headers: string;
    params: string;
    body_type: string;
    body: string;
    auth_type: string;
    auth_config: string;
    timeout_seconds: number;
    tests: string;
    pre_script: string;
    post_script: string;
  }
}

export namespace db {
  export interface TimingPhases {
    dns_lookup: number;
    tcp_handshake: number;
    tls_handshake: number;
    ttfb: number;
    download: number;
  }
}

export namespace httpclient {
  export interface AssertionResult {
    passed: boolean;
    expression: string;
    message?: string;
  }

  export interface ResponseResult {
    StatusCode: number;
    StatusText: string;
    Body: string;
    Headers: Record<string, string[]>;
    DurationMs: number;
    SizeBytes: number;
    TestResults?: AssertionResult[];
    Timing?: db.TimingPhases;
    consoleLogs?: string[];
    scriptErrors?: string[];
  }
}
