// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun() {
  return window['go']['main']['App']['CancelRun']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateEnvironment(arg1) {
  return window['go']['main']['App']['CreateEnvironment'](arg1);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateRequest(arg1, arg2) {
  return window['go']['main']['App']['CreateRequest'](arg1, arg2);
}

export function CreateRequestInFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRequestInFolder'](arg1, arg2, arg3);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function DeleteVariable(arg1) {
  return window['go']['main']['App']['DeleteVariable'](arg1);
}

export function DuplicateRequest(arg1) {
  return window['go']['main']['App']['DuplicateRequest'](arg1);
}

export function ExportCollection(arg1) {
  return window['go']['main']['App']['ExportCollection'](arg1);
}

export function ExportRequestAsCurl(arg1) {
  return window['go']['main']['App']['ExportRequestAsCurl'](arg1);
}

export function GetActiveEnvironment() {
  return window['go']['main']['App']['GetActiveEnvironment']();
}

export function GetDecryptedVariable(arg1, arg2) {
  return window['go']['main']['App']['GetDecryptedVariable'](arg1, arg2);
}

export function GetGlobalEnvironmentID() {
  return window['go']['main']['App']['GetGlobalEnvironmentID']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetVariables(arg1) {
  return window['go']['main']['App']['GetVariables'](arg1);
}

export function ImportCollection() {
  return window['go']['main']['App']['ImportCollection']();
}

export function ImportFromCurl(arg1, arg2) {
  return window['go']['main']['App']['ImportFromCurl'](arg1, arg2);
}

export function ListCollections() {
  return window['go']['main']['App']['ListCollections']();
}

export function ListEnvironments() {
  return window['go']['main']['App']['ListEnvironments']();
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListRequests(arg1) {
  return window['go']['main']['App']['ListRequests'](arg1);
}

export function MoveRequest(arg1, arg2) {
  return window['go']['main']['App']['MoveRequest'](arg1, arg2);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function RenameEnvironment(arg1, arg2) {
  return window['go']['main']['App']['RenameEnvironment'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RotateVarEncryptionKey() {
  return window['go']['main']['App']['RotateVarEncryptionKey']();
}

export function RunCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCollection'](arg1, arg2, arg3);
}

export function SearchRequests(arg1) {
  return window['go']['main']['App']['SearchRequests'](arg1);
}

export function SearchRequestsWithBody(arg1) {
  return window['go']['main']['App']['SearchRequestsWithBody'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function SetSecretVariable(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSecretVariable'](arg1, arg2, arg3);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetVariable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetVariable'](arg1, arg2, arg3, arg4);
}

export function ToggleVariableSecret(arg1, arg2) {
  return window['go']['main']['App']['ToggleVariableSecret'](arg1, arg2);
}

export function UpdateRequest(arg1) {
  return window['go']['main']['App']['UpdateRequest'](arg1);
}
