// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {httpclient} from '../models';
import {main} from '../models';

export function CreateCollection(arg1:string):Promise<db.Collection>;

export function CreateRequest(arg1:string,arg2:string):Promise<db.Request>;

export function DeleteCollection(arg1:string):Promise<void>;

export function GetRequest(arg1:string):Promise<db.Request>;

export function ListCollections():Promise<Array<db.Collection>>;

export function ListRequests(arg1:string):Promise<Array<db.Request>>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function SendRequest(arg1:string):Promise<httpclient.ResponseResult>;

export function UpdateRequest(arg1:main.RequestPayload):Promise<void>;
