// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {httpclient} from '../models';
import {main} from '../models';

export function ClearHistory():Promise<void>;

export function CreateCollection(arg1:string):Promise<db.Collection>;

export function CreateEnvironment(arg1:string):Promise<db.Environment>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<db.Folder>;

export function CreateRequest(arg1:string,arg2:string):Promise<db.Request>;

export function CreateRequestInFolder(arg1:string,arg2:string,arg3:string):Promise<db.Request>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string):Promise<void>;

export function DeleteVariable(arg1:number):Promise<void>;

export function DuplicateRequest(arg1:string):Promise<db.Request>;

export function ExportCollection(arg1:string):Promise<void>;

export function ExportRequestAsCurl(arg1:string):Promise<string>;

export function GetActiveEnvironment():Promise<string>;

export function GetGlobalEnvironmentID():Promise<string>;

export function GetHistory():Promise<Array<db.HistoryEntry>>;

export function GetRequest(arg1:string):Promise<db.Request>;

export function GetSetting(arg1:string):Promise<string>;

export function GetVariables(arg1:string):Promise<Array<db.EnvironmentVariable>>;

export function ImportCollection():Promise<db.Collection>;

export function ImportFromCurl(arg1:string,arg2:string):Promise<db.Request>;

export function ListCollections():Promise<Array<db.Collection>>;

export function ListEnvironments():Promise<Array<db.Environment>>;

export function ListFolders(arg1:string):Promise<Array<db.Folder>>;

export function ListRequests(arg1:string):Promise<Array<db.Request>>;

export function MoveRequest(arg1:string,arg2:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function RenameEnvironment(arg1:string,arg2:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function SendRequest(arg1:string):Promise<httpclient.ResponseResult>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetVariable(arg1:string,arg2:string,arg3:string):Promise<db.EnvironmentVariable>;

export function UpdateRequest(arg1:main.RequestPayload):Promise<void>;
